### ISSUE TITLE
Hey JPEG, it's Gavin

### ISSUE THREAD

**Issue by theJavin** [JPEGtheDev/Particle-Viewer#3]
I'm just trying to build the program so I can run it on the heart project code, and I can't seem to get it to build correctly. After running ./scripts/linuxPre.sh and ./scripts/linuxBuild.sh I get: "The Xinerama headers were not found" --Configuring incomplete, errors occurred!
I made sure to install all the dependencies listed so I don't know what's wrong. If it's something to do with cmake itself I'll have no idea since Dr. Wyatt never uses any kind of make. Any help is much appreciated! Thanks!

**Comment by JPEGtheDev** [comment]
> I'm just trying to build the program so I can run it on the heart project code, and I can't seem to get it to build correctly. After running ./scripts/linuxPre.sh and ./scripts/linuxBuild.sh I get: "The Xinerama headers were not found" --Configuring incomplete, errors occurred!
> I made sure to install all the dependencies listed so I don't know what's wrong. If it's something to do with cmake itself I'll have no idea since Dr. Wyatt never uses any kind of make. Any help is much appreciated! Thanks!


Ignore the linux pre and linux build scripts and just use cmake and make. those scripts are built for CI/CD and they havent been updated in forever. IIRC the correct build pipeline involves the following 

in the repo root do the following 

mkdir build
cd build
cmake ..
make

this is after doing a git pull and getting in all of the submodules.

let me get info on xinerama, are you guys running ubuntu still?

**Comment by JPEGtheDev** [comment]
looks like you dont have the xinerama dev libraries installed on that machine.

https://packages.ubuntu.com/focal/libxinerama-dev 

install this package and you should be good. if there is another xrandr library issue, maybe install the xorg-dev package

**Comment by theJavin** [comment]
Thanks so much! I don't know why my GitHub app on my phone didn't alert me to the messages, sorry for the late reply. I assumed it was a package issue but I couldn't find anything about dependencies. Yes, we're still running in Ubuntu which has been less of a blessing and more of a curse lately. 22.04 has not been as stable as previous versions. I'll get xinerama installed and let you know if I have any more problems.

Thanks again!

**Comment by theJavin** [comment]
I got it to build, thanks so much!
